apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tp0zh47ng-java-springboot
  janus-idp.io/tekton: tp0zh47ng-java-springboot
  backstage.io/kubernetes-id: tp0zh47ng-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tp0zh47ng-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
